### ISSUE TITLE
Generic build failure at openshift

### ISSUE THREAD

**Issue by robertosaavedr** [seanho00/reveal-multiplex#5]
Hello, I am having troubles at build the multiplex server, I have follow the instructions in the repo

at startup (internal/bootstrap/node.js:265:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
subprocess exited with status 1
subprocess exited with status 1
error: build error: error building at STEP "RUN /usr/libexec/s2i/assemble": exit status 1

**Comment by robertosaavedr** [comment]
remote.origin.url=https://github.com/seanho00/reveal-multiplex
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
---> Installing dependencies
[eval]:1
console.log(require('./package.json').scripts.build ? true : false)
                                             ^

TypeError: Cannot read property 'build' of undefined

**Comment by seanho00** [comment]
I'm so sorry, unfortunately I haven't updated this project in a long time!  The instructions were for the old version of OpenShift, which has since moved to a pure Kubernetes platform.  It would be lovely to write a docker and helm chart for this; it's really a very simple socket.io server, no bigger than a hello-world demo.
